/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191b23",
        "on-secondary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "primary-container": "#2563eb",
        primary: "#004ac6",
        outline: "#737686",
        tertiary: "#943700",
        surface: "#faf8ff",
        "tertiary-container": "#bc4800",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "surface-variant": "#e1e2ed",
        "outline-variant": "#c3c6d7",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#f0f0fb",
        "surface-container-high": "#e7e7f3",
        "surface-container": "#ededf9",
        "on-surface-variant": "#434655",
        "on-primary": "#ffffff",
        secondary: "#712ae2",
        "secondary-container": "#8a4cfc",
        "surface-container-highest": "#e1e2ed",
        background: "#faf8ff",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f3f3fe",
        "primary-fixed-dim": "#b4c5ff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        lg: "24px",
        "2xl": "48px",
        xs: "4px",
        "3xl": "64px",
        md: "16px",
        xl: "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
